---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-acs-secured-cluster-placement
  namespace: openshift-acm-policies
spec:
  clusterSets:
    - all-clusters