---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-all-placement
  namespace: openshift-acm-policies
spec:
  clusterSets:
    - aks-clusters
    - gke-clusters
