---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: acm-demo-namespace-policy-placement
  namespace: openshift-acm-policies
placementRef:
  name: policy-all-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: acm-demo-namespace-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy
