---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-acs-secured-cluster-placement-binding
  namespace: openshift-acm-policies
placementRef:
  name: policy-acs-secured-cluster-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-acs-secured-cluster
    apiGroup: policy.open-cluster-management.io
    kind: Policy

