kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: placements-app
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: placements-project
  source:
    path: manifests/base/placements
    repoURL: https://github.com/acm-demo/policies.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
       - CreateNamespace=true
       - PruneLast=true
       - RespectIgnoreDifferences=true
